### ISSUE TITLE
[PE-D][Tester D] Recipe feature bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113T-T09-3/tp#127]
![截圖 2023-03-31 下午6.02.41.png](https://raw.githubusercontent.com/chao2048/ped/main/files/4effdcc5-4417-44f6-b806-e13d56841053.png)

When the input index is too big, the program crashed.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: chao2048/ped#12

**Comment by aaronxujiachen** [comment]
Bug fixed
<img width="309" alt="Screenshot 2023-04-09 221910" src="https://user-images.githubusercontent.com/57344818/230778124-082686c2-504a-4eec-b48a-4b1ea692d750.png">
